const Map<String, dynamic> en = {
  "login": "Login",
  "welcome": "Welcome",
  "please_enter_email": "Please enter your email",
  "please_enter_password": "Please enter your password",
  "at_leaster_enter": "at least enter 4 characters",
  "please_enter_valid_email": "please enter valid email",
  "maximum_character": "maximum character is 50",
  "password" : "Password",
  "email" : "Email",
  "signup" : " Sign up",
  "not_have_account" : "Don\'t have an account?",
  "confidentiality" : "Login in means you accept our terms of use and privacy policy",
  "please_authenticate" : "Please authenticate",
  "error_message" : "Error Message",
  "email_or_password_not_found": "Email or Password not found",
  "please_enter_field": "please enter field",
  "dashboard": "Dash Board",
  "salesperson": "Salesperson",
  "settings": "Settings",
  "logout": "Logout",
  "statistics": "Statistics",
  "message": "Message",
  "view_all": "View All",
  "add": "Add",
  "create_account": "Create Account",
  "validate": "Validate",
  "salesperson_list": "Salesperson List",
  "loading": "Loading...",
  "reservation_list": "Reservations list",
  "made_reservation_from": " made reservation from ",
  "at_the_price_of": " at the price of ",
  "at": " at ",
  "Date": "Date ",
  "transactions_list": "Transactions list",
  "transactions": "Transactions",

};
