const Map<String, dynamic> fr = {
  "login": "Connexion",
  "welcome": "Bienvenu",
  "please_enter_email": "Veuillez entrer votre email",
  "please_enter_password": "s'il vous plait entrez votre mot de passe",
  "at_leaster_enter": "entrez au moins 4 caractères",
  "please_enter_valid_email": "veuillez entrer une adresse email valide",
  "maximum_character": "le caractère maximum est de 50",
  "password" : "Mot de passe",
  "email" : "Email",
  "signup" : " S'inscrire",
  "not_have_account" : "Vous n'avez pas de compte ?",
  "confidentiality" : "Vous connecter signifie que vous acceptez nos conditions d'utilisation et notre politique de confidentialité",
  "please_authenticate" : "Veuillez vous authentifier",
  "error_message" : "Message d'erreur",
  "email_or_password_not_found": "Email ou mot de passe introuvable",
  "please_enter_field": "Veuillez remplir le champs",
  "dashboard": "Tableau de Bord",
  "salesperson": "Commerciaux",
  "settings": "Configurations",
  "logout": "Déconnexion",
  "statistics": "Statistiques",
  "message": "Message",
  "view_all": "Voir Tout",
  "add": "Ajouter",
  "create_account": "Créer un Compte",
  "validate": "Valider",
  "salesperson_list": "Liste des Commerciaux",
  "loading": "Chargement Encours...",
  "reservation_list": "Liste Reservations",
  "made_reservation_from": " a d'éffectué une réservation de ",
  "at_the_price_of": " au prix de ",
  "at": " à ",
  "Date": "Date ",

};
